-- 全てのユーザーのVISIONを削除
DELETE FROM MANDALA_VISION;

-- ユーザーIDが1以外のVISIONを削除
DELETE FROM MANDALA_VISION WHERE VISION_ID <> 1;

-- ユーザーIDが1と2以外のVISIONを削除
DELETE FROM MANDALA_VISION WHERE VISION_ID NOT IN (1, 2);