-- 全てのユーザーのACTIONSを削除
DELETE FROM MANDALA_ACTIONS;

-- ユーザーIDが1以外のACTIONSを削除
DELETE FROM MANDALA_ACTIONS WHERE ELEMENT_ID NOT BETWEEN 1 AND 8;

-- ユーザーID 2の要素8に関連するアクションを削除
DELETE FROM MANDALA_ACTIONS
WHERE ELEMENT_ID = 16;

-- ユーザーIDが1（翔平）と2（美和1）以外のデータを削除
DELETE FROM USERS
WHERE USER_ID NOT IN (1, 2);
