-- 外部キーの依存関係に従って順序よく削除
DROP TABLE IF EXISTS HUB_LIKES;
DROP TABLE IF EXISTS HUB_POSTS;
DROP TABLE IF EXISTS MANDALA_ACTIONS;
DROP TABLE IF EXISTS MANDALA_ELEMENTS;
DROP TABLE IF EXISTS MANDALA_VISION;
DROP TABLE IF EXISTS USERS;

